// The Pit — /simulate page frontend test.
//
// Loads the REAL server-rendered page HTML into jsdom (scripts run), with a
// stubbed fetch and a recording canvas 2d context. The canned /api/v1/simulate
// response is generated by calling the REAL postSimulate route with a mock
// D1, so the test exercises the page against the true API shape.

import { describe, it, expect, afterEach } from 'vitest';
import { JSDOM } from 'jsdom';
import { simulatePage } from '../src/pages';
import { postSimulate, resetSimulateRateLimit } from '../src/routes/simulate';
import type { Env } from '../src/lib/types';

const MN = Date.UTC(2025, 8, 20); // 2025-09-20
const MX = Date.UTC(2026, 8, 20); // 2026-09-20

function mockDb() {
  const stmt = (sql: string) => {
    const bound = (..._p: unknown[]) => ({
      all: async () => {
        if (sql.includes('WITH needs(ts)')) {
          const hits = sql.match(/\(\d+\)/g) ?? [];
          return {
            results: hits.map((x) => {
              const ts = Number(x.slice(1, -1));
              const mid = 60000 + ((ts / 3_600_000) % 24) * 10;
              return { need_ts: ts, bid: mid - 50, ask: mid + 50 };
            }),
          };
        }
        return { results: [] };
      },
      first: async () => {
        if (sql.includes('MIN(ts)')) return { mn: MN, mx: MX };
        return null;
      },
      run: async () => ({ success: true }),
    });
    return { bind: bound, all: () => bound().all(), first: () => bound().first(), run: () => bound().run() };
  };
  return { DB: { prepare: stmt }, ADMIN_SECRET: 'x' } as unknown as Env;
}

type CtxCall = [string, unknown[]];

function makeCtx(): { calls: CtxCall[] } & Record<string, unknown> {
  const calls: CtxCall[] = [];
  const grad = { addColorStop() {} };
  const proxy = new Proxy(
    {},
    {
      get(_t, prop: string) {
        if (prop === 'calls') return calls;
        return (...args: unknown[]) => {
          calls.push([prop, args]);
          if (prop === 'createLinearGradient') return grad;
          if (prop === 'measureText') return { width: 42 };
          return undefined;
        };
      },
      set() {
        return true;
      },
    },
  );
  return proxy as { calls: CtxCall[] } & Record<string, unknown>;
}

interface Seen {
  url?: string;
  body?: string;
}

let wins: Array<{ close: () => void }> = [];
afterEach(() => {
  for (const w of wins) w.close();
  wins = [];
});

interface CannedSpec {
  pair: string;
  side: 'long' | 'short';
  notional: number;
  timestamp: number;
}

async function loadPage(cannedSpecs?: CannedSpec[], bodyExtra?: Record<string, unknown>) {
  resetSimulateRateLimit();
  const env = mockDb();

  // Canned response from the REAL route (true API shape).
  const span = MX - MN;
  const specs: CannedSpec[] =
    cannedSpecs ??
    [0.18, 0.4, 0.62, 0.85].map((f, i) => ({
      pair: 'BTC/USD',
      side: i % 2 === 0 ? 'long' : ('short' as const),
      notional: 2000 - i * 400,
      timestamp: Math.round(MN + span * f),
    }));
  const simReq = new Request('https://the-pit.twj.workers.dev/api/v1/simulate', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ starting_capital: 10000, trades: specs, ...(bodyExtra ?? {}) }),
  });
  const simRes = await postSimulate(simReq, env);
  expect(simRes.status).toBe(200);
  const canned = await simRes.json();

  const html = await (await simulatePage(env)).text();
  const seen: Seen = {};
  const ctxs: Array<{ calls: CtxCall[] }> = [];

  const dom = new JSDOM(html, {
    url: 'https://the-pit.twj.workers.dev/simulate',
    runScripts: 'dangerously',
    beforeParse(window: unknown) {
      const w = window as Record<string, unknown>;
      w.fetch = async (url: unknown, init?: { body?: string }) => {
        const u = String(url);
        if (u.includes('/api/v1/simulate')) {
          seen.url = u;
          seen.body = init?.body;
          return { ok: true, status: 200, json: async () => canned };
        }
        return { ok: false, status: 404, json: async () => null };
      };
      const proto = (w.HTMLCanvasElement as unknown as { prototype: object }).prototype;
      Object.defineProperty(proto, 'getContext', {
        configurable: true,
        value: function (this: object) {
          const c = makeCtx();
          (this as Record<string, unknown>)._ctx = c;
          ctxs.push(c);
          return c;
        },
      });
    },
  });
  wins.push(dom.window);
  const { document } = dom.window;
  return { window: dom.window, document, seen, ctxs };
}

const tick = (ms = 80) => new Promise((r) => setTimeout(r, ms));

describe('/simulate page', () => {
  it('renders the simulator UI with derived history range (no hardcoded dates)', async () => {
    const { document } = await loadPage();
    const ctl = document.getElementById('simCtl');
    expect(ctl).not.toBeNull();
    expect(ctl!.getAttribute('data-hist-from')).toBe(String(MN));
    expect(ctl!.getAttribute('data-hist-to')).toBe(String(MX));
    // History note derives the range from data, not hardcoded copy.
    expect(document.body.textContent).toContain('Sep 2025');
    expect(document.body.textContent).toContain('Sep 2026');
    // Pair selector: 5 pairs, BTC active by default.
    const btns = document.querySelectorAll('#simPairs button');
    expect(btns.length).toBe(5);
    expect(btns[0].classList.contains('on')).toBe(true);
    expect(btns[0].getAttribute('data-pair')).toBe('BTC/USD');
    // Nav links the page.
    expect(document.querySelector('.links a[href="/simulate"]')).not.toBeNull();
  });

  it('Guided example -> 4 annotated June trades + timeframe; Run -> results render in place, no reload', async () => {
    const { window, document, seen, ctxs } = await loadPage();
    const hrefBefore = window.location.href;

    document.getElementById('simExample')!.dispatchEvent(
      new window.MouseEvent('click', { bubbles: true }),
    );
    const rows = document.querySelectorAll('#simRows tr');
    expect(rows.length).toBe(4);
    // Sides alternate long/short via the toggle buttons.
    const sides = Array.from(rows).map((tr: Element) => {
      const on = tr.querySelector('.seg button.on-long,.seg button.on-short')!;
      return on.getAttribute('data-side');
    });
    expect(sides).toEqual(['long', 'short', 'long', 'short']);
    // The guided example prefills the June 2026 timeframe.
    const fromEl = document.getElementById('simFrom') as HTMLInputElement;
    const toEl = document.getElementById('simTo') as HTMLInputElement;
    expect(fromEl.value).toContain('2026-06-01');
    expect(toEl.value).toContain('2026-06-20');
    // The empty-state mini-guide hides once trades exist.
    expect((document.getElementById('simGuide') as HTMLElement).hidden).toBe(true);

    // Give the canvas a size so the chart draws (jsdom reports 0 otherwise).
    const cv = document.getElementById('simChart')!;
    Object.defineProperty(cv, 'clientWidth', { value: 800, configurable: true });
    Object.defineProperty(cv, 'clientHeight', { value: 300, configurable: true });

    document.getElementById('simRun')!.dispatchEvent(
      new window.MouseEvent('click', { bubbles: true }),
    );
    await tick();

    // The request went out as a single POST with the guided trades + timeframe.
    expect(seen.url).toContain('/api/v1/simulate');
    const sent = JSON.parse(seen.body!);
    expect(sent.starting_capital).toBe(10000);
    expect(sent.trades.length).toBe(4);
    expect(sent.trades.every((t: { pair: string }) => t.pair === 'BTC/USD')).toBe(true);
    expect(sent.trades.map((t: { timestamp: number }) => t.timestamp)).toEqual([
      Date.UTC(2026, 5, 2, 3, 0),
      Date.UTC(2026, 5, 4, 1, 0),
      Date.UTC(2026, 5, 5, 18, 0),
      Date.UTC(2026, 5, 8, 14, 0),
    ]);
    expect(sent.from).toBe(Date.UTC(2026, 5, 1, 0, 0));
    expect(sent.to).toBe(Date.UTC(2026, 5, 20, 0, 0));

    // Results render without a page reload.
    expect(window.location.href).toBe(hrefBefore);
    const resEl = document.getElementById('simResults')!;
    expect(resEl.hidden).toBe(false);
    const summary = document.getElementById('simSummary')!.textContent!;
    expect(summary).toContain('hypothetical');
    const stats = document.querySelectorAll('#simStats .stat');
    expect(stats.length).toBe(4);
    const labels = Array.from(stats).map((s: Element) => s.querySelector('.k')!.textContent);
    expect(labels).toEqual(['Final equity', 'Total return', 'Max drawdown', 'Sharpe']);
    // Per-trade breakdown rows.
    expect(document.querySelectorAll('#simTradeRows tr').length).toBe(4);
    // Equity curve actually drew on the canvas.
    expect(ctxs.length).toBeGreaterThan(0);
    const drawn = ctxs[0].calls.map((c) => c[0]);
    expect(drawn).toContain('lineTo');
    expect(drawn).toContain('stroke');
  });

  it('Run with no trades shows an inline error and no results', async () => {
    const { window, document, seen } = await loadPage();
    document.getElementById('simRun')!.dispatchEvent(
      new window.MouseEvent('click', { bubbles: true }),
    );
    await tick();
    const errEl = document.getElementById('simErr')!;
    expect(errEl.hidden).toBe(false);
    expect(errEl.textContent).toContain('at least one trade');
    expect(document.getElementById('simResults')!.hidden).toBe(true);
    expect(seen.url).toBeUndefined(); // no request fired
  });

  it('server errors surface inline (e.g. rate limit)', async () => {
    const { window, document } = await loadPage();
    // Swap the fetch stub for this page to return a 429.
    (window as unknown as Record<string, unknown>).fetch = async () => ({
      ok: false,
      status: 429,
      json: async () => ({ error: { code: 'rate_limited', message: 'Too many simulation requests' } }),
    });
    document.getElementById('simExample')!.dispatchEvent(
      new window.MouseEvent('click', { bubbles: true }),
    );
    document.getElementById('simRun')!.dispatchEvent(
      new window.MouseEvent('click', { bubbles: true }),
    );
    await tick();
    const errEl = document.getElementById('simErr')!;
    expect(errEl.hidden).toBe(false);
    expect(errEl.textContent).toContain('Too many simulation requests');
    expect(document.getElementById('simResults')!.hidden).toBe(true);
  });

  it('replay charts: pair tabs switch series, markers drawn, tooltip, play toggles, row hover', async () => {
    const span = MX - MN;
    const specs = [0.18, 0.4, 0.62, 0.85].map((f, i) => ({
      pair: i % 2 === 0 ? 'BTC/USD' : 'ETH/USD',
      side: (i % 2 === 0 ? 'long' : 'short') as 'long' | 'short',
      notional: 2000 - i * 400,
      timestamp: Math.round(MN + span * f),
    }));
    const { window, document } = await loadPage(specs);

    // Build one valid row so Run passes validation; the canned response is what renders.
    document.getElementById('simExample')!.dispatchEvent(
      new window.MouseEvent('click', { bubbles: true }),
    );
    const mkt = document.getElementById('simMarketChart')!;
    const eq = document.getElementById('simChart')!;
    for (const [cv, h] of [[mkt, 250], [eq, 280]] as const) {
      Object.defineProperty(cv, 'clientWidth', { value: 800, configurable: true });
      Object.defineProperty(cv, 'clientHeight', { value: h, configurable: true });
      Object.defineProperty(cv, 'getBoundingClientRect', {
        value: () => ({ left: 0, top: 0, width: 800, height: h, right: 800, bottom: h }),
        configurable: true,
      });
    }
    document.getElementById('simRun')!.dispatchEvent(
      new window.MouseEvent('click', { bubbles: true }),
    );
    await tick();
    expect(document.getElementById('simResults')!.hidden).toBe(false);

    // Pair tabs: one per traded pair; BTC active first.
    const tabs = document.querySelectorAll('#simPairTabs button');
    expect(tabs.length).toBe(2);
    expect(tabs[0].textContent).toBe('BTC/USD');
    expect(tabs[0].classList.contains('on')).toBe(true);
    // Two filled BTC trades -> two markers on the market chart.
    expect(mkt.dataset.markers).toBe('2');

    // Switching tabs swaps the series (2 ETH markers).
    (tabs[1] as HTMLElement).dispatchEvent(new window.MouseEvent('click', { bubbles: true }));
    expect(tabs[1].classList.contains('on')).toBe(true);
    expect(mkt.dataset.markers).toBe('2');

    // Hovering shows the tooltip with equity info.
    mkt.dispatchEvent(
      new window.MouseEvent('pointermove', { bubbles: true, clientX: 400, clientY: 100 }),
    );
    const tip = document.getElementById('simTip')!;
    expect(tip.style.display).toBe('block');
    expect(tip.textContent).toContain('Equity');
    mkt.dispatchEvent(new window.MouseEvent('pointerleave', { bubbles: true }));
    expect(tip.style.display).toBe('none');

    // Row hover highlights the marker - checked before the play toggles below,
    // because pressing play while the playhead sits at the end restarts the
    // replay from the beginning, hiding future markers (progressive reveal).
    const rows = document.querySelectorAll('#simTradeRows tr');
    expect(rows.length).toBe(4);
    (rows[1] as HTMLElement).dispatchEvent(new window.MouseEvent('mouseover', { bubbles: true }));
    expect(mkt.dataset.hit).toBe('1');
    document
      .getElementById('simTradeRows')!
      .dispatchEvent(new window.MouseEvent('mouseleave', { bubbles: true }));
    expect(mkt.dataset.hit).toBe('-1');

    // Play button toggles between play and pause glyphs.
    const play = document.getElementById('simPlay')!;
    expect(play.innerHTML).toContain('\u25b6');
    play.dispatchEvent(new window.MouseEvent('click', { bubbles: true }));
    expect(play.innerHTML).toContain('\u23f8');
    play.dispatchEvent(new window.MouseEvent('click', { bubbles: true }));
    expect(play.innerHTML).toContain('\u25b6');
  });

  it('transport: reset/step/event-jump/scrub/keyboard update the moment panel; tour walks the guided scenario', async () => {
    // Guided-scenario trades on the real June-2026 window.
    const gts = [Date.UTC(2026, 5, 2, 3, 0), Date.UTC(2026, 5, 4, 1, 0), Date.UTC(2026, 5, 5, 18, 0), Date.UTC(2026, 5, 8, 14, 0)];
    const gsides = ['long', 'short', 'long', 'short'] as const;
    const gnot = [2000, 1500, 1000, 800];
    const specs = gts.map((timestamp, i) => ({
      pair: 'BTC/USD',
      side: gsides[i],
      notional: gnot[i],
      timestamp,
    }));
    const { window, document } = await loadPage(specs, {
      from: Date.UTC(2026, 5, 1, 0, 0),
      to: Date.UTC(2026, 5, 20, 0, 0),
    });

    document.getElementById('simExample')!.dispatchEvent(
      new window.MouseEvent('click', { bubbles: true }),
    );
    const mkt = document.getElementById('simMarketChart')!;
    const eq = document.getElementById('simChart')!;
    for (const [cv, h] of [[mkt, 250], [eq, 280]] as const) {
      Object.defineProperty(cv, 'clientWidth', { value: 800, configurable: true });
      Object.defineProperty(cv, 'clientHeight', { value: h, configurable: true });
      Object.defineProperty(cv, 'getBoundingClientRect', {
        value: () => ({ left: 0, top: 0, width: 800, height: h, right: 800, bottom: h }),
        configurable: true,
      });
    }
    document.getElementById('simRun')!.dispatchEvent(
      new window.MouseEvent('click', { bubbles: true }),
    );
    await tick();
    expect(document.getElementById('simResults')!.hidden).toBe(false);

    const clock = () => document.getElementById('simClock')!.textContent!;
    const click = (id: string) =>
      document.getElementById(id)!.dispatchEvent(new window.MouseEvent('click', { bubbles: true }));

    // All transport controls are present, incl. speed selector and scrub slider.
    for (const id of ['simReset', 'simPrevEv', 'simStepB', 'simPlay', 'simStepF', 'simNextEv', 'simSpeed', 'simScrub', 'simTourBtn']) {
      expect(document.getElementById(id), id).not.toBeNull();
    }
    // Event ticks: one per filled trade.
    expect(document.querySelectorAll('#simTicks .simtick').length).toBe(4);

    // Moment panel shows equity / P&L / drawdown at the playhead (window end after render).
    expect(clock()).toContain('Jun 20');
    const moment = document.getElementById('simMoment')!.textContent!;
    expect(moment).toContain('Equity');
    expect(moment).toContain('P&L');
    expect(moment).toContain('Drawdown from peak');

    // Clicking a revealed fill marker jumps the playhead straight to that trade.
    const marks = (mkt as unknown as { _simMarks: Array<{ x: number; y: number; ts: number }> })._simMarks.slice();
    expect(marks.length).toBe(4);
    click('simReset');
    expect(clock()).toContain('Jun 1');
    mkt.dispatchEvent(
      new window.MouseEvent('click', { bubbles: true, clientX: marks[3].x, clientY: marks[3].y }),
    );
    expect(clock()).toContain('Jun 8');

    // Reset -> playhead at the start; every trade is "upcoming" in the inspector.
    click('simReset');
    expect(clock()).toContain('Jun 1');
    const inspRows = document.querySelectorAll('#simInspectRows tr');
    expect(inspRows.length).toBe(4);
    expect(document.querySelectorAll('#simInspectRows tr.tr-upcoming').length).toBe(4);
    expect(document.getElementById('simNetPos')!.textContent).toContain('No open positions');

    // Step forward moves the playhead.
    const before = clock();
    click('simStepF');
    expect(clock()).not.toBe(before);

    // Jump to next trade event lands on the first fill; its row flips to open.
    click('simReset');
    click('simNextEv');
    expect(clock()).toContain('Jun 2');
    expect(document.querySelectorAll('#simInspectRows tr.tr-open').length).toBe(1);
    expect(document.querySelectorAll('#simInspectRows tr.tr-upcoming').length).toBe(3);
    // Jump back goes to the start again.
    click('simPrevEv');
    expect(clock()).toContain('Jun 1');

    // Scrub slider moves the playhead.
    const sc = document.getElementById('simScrub') as HTMLInputElement;
    const c0 = clock();
    sc.value = '500';
    sc.dispatchEvent(new window.Event('input', { bubbles: true }));
    expect(clock()).not.toBe(c0);

    // Keyboard: ArrowRight steps, Space toggles play.
    const c1 = clock();
    document.dispatchEvent(new window.KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true }));
    expect(clock()).not.toBe(c1);
    const play = document.getElementById('simPlay')!;
    document.dispatchEvent(new window.KeyboardEvent('keydown', { code: 'Space', key: ' ', bubbles: true }));
    expect(play.innerHTML).toContain('\u23f8');
    document.dispatchEvent(new window.KeyboardEvent('keydown', { code: 'Space', key: ' ', bubbles: true }));
    expect(play.innerHTML).toContain('\u25b6');

    // Clicking the chart jumps the playhead there.
    const c2 = clock();
    mkt.dispatchEvent(new window.MouseEvent('click', { bubbles: true, clientX: 400, clientY: 100 }));
    expect(clock()).not.toBe(c2);

    // Speed selector changes the value the player reads.
    const speed = document.getElementById('simSpeed') as unknown as HTMLSelectElement;
    speed.value = '4';
    speed.dispatchEvent(new window.Event('change', { bubbles: true }));
    expect(speed.value).toBe('4');

    // Guided tour: intro -> trade steps with captions -> outro.
    click('simTourBtn');
    const bar = document.getElementById('simTourBar')!;
    expect(bar.hidden).toBe(false);
    expect(document.getElementById('simTourStep')!.textContent).toContain('Step 1 of 6');
    expect(document.getElementById('simTourCap')!.textContent).toContain('June 2026');
    expect(clock()).toContain('Jun 1');
    click('simTourNext');
    expect(document.getElementById('simTourStep')!.textContent).toContain('Step 2 of 6');
    expect(document.getElementById('simTourCap')!.textContent).toContain('Bet 1');
    expect(clock()).toContain('Jun 2');
    // Walk to the outro.
    for (let i = 0; i < 4; i++) click('simTourNext');
    expect(document.getElementById('simTourStep')!.textContent).toContain('Step 6 of 6');
    expect(document.getElementById('simTourCap')!.textContent).toContain('Final score');
    click('simTourBack');
    expect(document.getElementById('simTourStep')!.textContent).toContain('Step 5 of 6');
    click('simTourEnd');
    expect(bar.hidden).toBe(true);
  });
});
